"""add name and dscr

Revision ID: 57fc5129422e
Revises: 667f30c6da97
Create Date: 2025-03-09 16:04:25.897361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57fc5129422e'
down_revision: Union[str, None] = '667f30c6da97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('documents_contract_id_fkey', 'documents', type_='foreignkey')
    op.drop_column('documents', 'contract_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('contract_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('documents_contract_id_fkey', 'documents', 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
