"""add name and dscr

Revision ID: 667f30c6da97
Revises: 873430260b62
Create Date: 2025-03-09 15:57:29.287085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '667f30c6da97'
down_revision: Union[str, None] = '873430260b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('name', sa.String(), nullable=False))
    op.add_column('contracts', sa.Column('discription', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('name', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('discription', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'discription')
    op.drop_column('documents', 'name')
    op.drop_column('contracts', 'discription')
    op.drop_column('contracts', 'name')
    # ### end Alembic commands ###
