"""FIX MtM

Revision ID: bb161a072e6f
Revises: 8d4d9346a90c
Create Date: 2025-03-09 19:16:12.279086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb161a072e6f'
down_revision: Union[str, None] = '8d4d9346a90c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'contracts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'user_id')
    # ### end Alembic commands ###
